trainingInput:
  scaleTier: CUSTOM
  masterType: n1-highmem-96
  masterConfig:
    diskConfig:
      bootDiskSizeGb: 3000
      bootDiskType: pd-ssd
  args:
    - --bz-features-path=gs://etldata-prod-search-ranking-data-hkwv8r/user/yfu/purchase_7days/data/pyspark_buzzsaw_features/2021-01-06_2021-01-12/results/part-*
    - --bz-features-path-test=gs://etldata-prod-search-ranking-data-hkwv8r/user/yfu/purchase_7days/data/pyspark_buzzsaw_features/2021-01-13_2021-01-19/results/part-000*
    - --tree-config-path=gs://etldata-prod-search-ranking-data-hkwv8r/data/shared/ranking/lightgbm/tree_train_fe_v2.conf
    - --pretrained-model-path=gs://etldata-prod-search-ranking-data-hkwv8r/user/yfu/multi_test/pretrained/2020-12-02-2021-01-05.csr_dresden_lgbm_model_lambdamart_perso_v2_window_35days_newqtc/model
    - --output-model-path=gs://etldata-prod-search-ranking-data-hkwv8r/user/yfu/multi-test/post_trained/models/test_7days/
    - --num_trees=500 #Override the default parameter for num_trees, don't HP tune on this
#  hyperparameters:
#    goal: MAXIMIZE
#    hyperparameterMetricTag: validation_ndcg
#    maxTrials: 1
#    maxParallelTrials: 1
#    params: #HP Tune on these
#      - parameterName: num_leaves
#        type: INTEGER
#        minValue: 16
#        maxValue: 127
#        scaleType: UNIT_LINEAR_SCALE
