trainingInput:
  scaleTier: CUSTOM
  masterType: n1-highmem-96
  masterConfig:
    diskConfig:
      bootDiskSizeGb: 3000
      bootDiskType: pd-ssd
  args:
    - --bz-features-path=gs://etldata-prod-search-ranking-data-hkwv8r/data/shared/ranking/lightgbm/data/pyspark_buzzsaw_features_multiobj_v1_7days/2021-03-01_2021-03-07/results/part-*
    - --bz-features-path-test=gs://etldata-prod-search-ranking-data-hkwv8r/data/shared/ranking/lightgbm/data/pyspark_buzzsaw_features_multiobj_v1_7days/2021-03-08_2021-03-14/results/part-000*
    - --tree-config-path=gs://etldata-prod-search-ranking-data-hkwv8r/data/shared/ranking/lightgbm/tree_train_mobj_v1.conf
    - --pretrained-model-path=gs://etldata-prod-search-ranking-data-hkwv8r/user/yfu/multi_test/pretrained/models/model
    - --output-model-path=gs://etldata-prod-search-ranking-data-hkwv8r/user/yfu/multi-test/post_trained/models/test_7days/
    - --num_trees=500 #Override the default parameter for num_trees, don't HP tune on this
#  hyperparameters:
#    goal: MAXIMIZE
#    hyperparameterMetricTag: validation_ndcg
#    maxTrials: 1
#    maxParallelTrials: 1
#    params: #HP Tune on these
#      - parameterName: num_leaves
#        type: INTEGER
#        minValue: 16
#        maxValue: 127
#        scaleType: UNIT_LINEAR_SCALE
